### ISSUE TITLE
system notification 

### ISSUE THREAD

**Issue by abdullahCode511** [zalsaeed/cgav#16]
make all the notification appear as soon as something happen without the need to refresh the page (like change password )

**Comment by zalsaeed** [comment]
The issue appears on the settings page, the download page, the home page.

**Comment by zalsaeed** [comment]
In addition to the abovementioned issues, we need to unify the notification type by converting flash messages to popup messages.

**Comment by abdullahCode511** [comment]
### template page

- [ ] add new template 

- [ ] edit template
### users settings /admin page 

- [ ] edit user name 

- [ ] edit user email

- [ ] edit user password

- [ ] delete user 
### Activity page 

- [ ] add new activity

**Comment by abdullahCode511** [comment]
There are too many conditions involved in adding a new activity, so I decided not to change it. If this page needs to be the same as the other pages to finish V1, I will need the help of the person who created the functions to keep track of the conditions.

**Comment by abdullahCode511** [comment]
> There are too many conditions involved in adding a new activity, so I decided not to change it. If this page needs to be the same as the other pages to finish V1, I will need the help of the person who created the functions to keep track of the conditions.
