### ISSUE TITLE
fix the "add_event" page to allow adding a bilingual certificate. 

### ISSUE THREAD

**Issue by zalsaeed** [zalsaeed/cgav#19]
The `Add Event` page should allow users to add a bilingual language. However, the duality in the language is not mandatory. Thus, the user should be able to language A, B, or both. 

NOTE:
Some fields are in a single language, and others are in a bilanguage. 
Single language fields:
- event title
- presenter name
- secret phrase
- event type
- date
- certificate template 
- signature fields (name/position/image)
bilanguage fields:
- greetings (female/male)
- recipient title (female/male)
- intro 
- event description (female/male)

Possible tasks: 

- [x] Add the Ar language form 
- [x] Add the En language form
- [x] Add a button/toggle for each language to show or hide the fields. 
- [x] Validate that the user selected at least one language. Otherwise, the user should not be able to submit the event info. 
- [x] If a user selects a language, then the user must fill in its fields.

**Comment by abdullahCode511** [comment]
the front-end is ready 
now we need to link it to the back-end
