### ISSUE TITLE
enhance the preview for the template to include choosing a color and adding a text

### ISSUE THREAD

**Issue by zalsaeed** [zalsaeed/cgav#25]
Just like the x,y, height, and width for each field in the certificate, the user should be able to pick a color and should be able to insert a text that they can preview immediately.

**Comment by ralhazmi** [comment]
I added two fields on the edit template page, one to allow the user to change the color of items in the certificate and one to allow the user to add alt text in the preview for example to see if placement is good for very long student names in the certificate. The student's name can be typed as an alternative to the automatic text that displays in the preview
