### ISSUE TITLE
Implement Salting/Hashing by combining (Secret Phrase+Generated Hash) for Improved Security 

### ISSUE THREAD

**Issue by wesamhamad** [zalsaeed/cgav#44]

**Comment by zalsaeed** [comment]
Isn't this what the function 
https://github.com/zalsaeed/cgav/blob/dd1710cabf89b32b7ebd145f4f8acc080e9c9e6d/src/flask_website/util.py#L11-L22

and the usage at 

https://github.com/zalsaeed/cgav/blob/dd1710cabf89b32b7ebd145f4f8acc080e9c9e6d/src/flask_website/certificate.py#L45

is for?

**Comment by wesamhamad** [comment]
Yes, the `small_hash` function generates a hash (random string). However, the aspect I'm addressing in the issue title involves appending an additional phrase (known as Salting), provided by the user during the 'add event' form submission. This extra step is crucial for enhancing security when storing the hash in the database.Salting is optional, instead we may include encryption for added security measures.
