### ISSUE TITLE
Personalize the email body

### ISSUE THREAD

**Issue by zalsaeed** [zalsaeed/cgav#61]
The emails the system send to deliver the certificates is now fetching some information for the recipient (e.g., the recipient name). Given the data is already fetched, we should personalize the email body as much as we can. For example, include the event name, date, etc.

**Comment by SalmanSaleh1** [comment]
**if user select Arabic email content**
![image](https://github.com/zalsaeed/cgav/assets/138271238/06ec443e-8605-4bff-9462-b9b6215eeae2)


**English:**
![image](https://github.com/zalsaeed/cgav/assets/138271238/cb24d1ac-1c8e-4308-b37c-158a536234fe)

**Comment by SalmanSaleh1** [comment]
- [ ] Add a button to let users choose whether to display event information in email(Event title, event date, recipient name, presenter name)

**Comment by SalmanSaleh1** [comment]
Done.
