### ISSUE TITLE
Preview of the default email body

### ISSUE THREAD

**Issue by zalsaeed** [zalsaeed/cgav#62]
By default the system provides a nice title and body that will be used when sending an email (with the ability to customize it). As the system will be used irregularly, the user should have a chance to always preview the default title and body just as a conformation of what will be sent.

**Comment by SalmanSaleh1** [comment]
![image](https://github.com/zalsaeed/cgav/assets/138271238/a076ec63-cc2e-4b37-9191-ee7006c62656)
![image](https://github.com/zalsaeed/cgav/assets/138271238/1d15acfe-536b-45b9-b57e-fc52d58c3fea)

**Comment by SalmanSaleh1** [comment]
Enhance the email page style:

- [ ] Move the preview to the right of the email select.
- [ ] Place the email select in a box with a limited size and add a scroll to show more emails.
