### ISSUE TITLE
Session management doesn't work

### ISSUE THREAD

**Issue by zalsaeed** [zalsaeed/cgav#72]
As of the last demo the session management does not work. More information needs to be collected about this issue (i.e., give an example) and it needs to be fixed before we deploy the system.

**Comment by abdullahCode511** [comment]
There was a logic error with the root route and the certificate page route; somehow, they were conflicting. It has now been properly fixed.

**Comment by zalsaeed** [comment]
- Test the log-out case and see if it works or not. 

If the log-out works, then this ticket should be closed.

**Comment by abdullahCode511** [comment]
done after testing 

"closed the browser, search again localhos, /logout "
