### ISSUE TITLE
Fix the language switch when in AR mode within the settings page

### ISSUE THREAD

**Issue by zalsaeed** [zalsaeed/cgav#73]
When we are using the Arabic language and go to the settings the language switch will disappear behind some other interface content. This should be fixed by either changing the bar to not interfere with the nav-bar or by shifting the language switch in this page in on this page only.

**Comment by KAbaalkhail** [comment]
After reviewing the user and admin access pages, no issues were found in switching between the pages.

**Comment by KAbaalkhail** [comment]
still problem exsist
