### ISSUE TITLE
users table id field 

### ISSUE THREAD

**Issue by abdullahCode511** [zalsaeed/cgav#8]
when i add a new user an error show up that seys there is no default value for the user_id

temporarily solution
i added a new field in the register form and named it ID and added a condition to prevent duplicated ID's

in the register function
`id = StringField(validators=[
                           InputRequired()], render_kw={"placeholder": "user_id"})`

in the register.html
`<form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ form.user_name }}
        {{ form.id }}
        {{ form.password }}
        {{ form.submit }}
    </form>`

**Comment by zalsaeed** [comment]
fixed
